### ISSUE TITLE
Deploy plugin to site additively.

### ISSUE THREAD

**Issue by ingokuba** [intensiongmbh/lizzy#23]
When deploying: Rename `latest` to `release-[number]` and deploy new one to `latest`.

**Comment by ingokuba** [comment]
@rbauer-int question: if I deploy multiple artifacts to the site - must I not exceed a certain limit of storage space on the server?

**Comment by rbauer-int** [comment]
Hi @ingokuba No worries about storage space!
But think about publishing only versions you want to support. Especially if there are bug fix releases, the previous versions should be removed so users don't accidentally install buggy versions. 
So versions that are no longer supported or are error prone should be removed.

**Comment by ingokuba** [comment]
Hello @intensiongmbh/devteam 
I have a question about how to handle the replacement of ressources on the server.
In this picture I displayed the simple solution - you can choose between:
- **deploy**: create new release and deploy to `latest` folder; previous release into `release-[number]`
- **bugfix**: create new release and replace previous release (in `latest`)
![build](https://user-images.githubusercontent.com/42644709/45896596-f4a57280-bdd4-11e8-9b0d-13a927701ed9.png)
Option 2: specify release number of the release which should be replaced. If none is passed just **deploy**. I don't know how or whether this is possible in CircleCI though.
